# Dockerfile for React (frontend)
FROM node:18-alpine as build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json /app/
RUN npm install

# Copy project files
COPY . /app/

# Build the React app and Serve the app
RUN npm run build


FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/build /app/build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
