# Generated by Django 5.1.4 on 2024-12-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("start_row", models.IntegerField(default=1)),
                ("start_column", models.IntegerField(default=1)),
                ("columns", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("errors", models.JSONField(blank=True, null=True)),
                (
                    "excel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excel_parcer.exceltype",
                    ),
                ),
            ],
        ),
    ]
