# Generated by Django 5.1.4 on 2024-12-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_parcer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
