# Dockerfile for Django (backend)
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app/

RUN python3 -m pip install --no-cache-dir -r requirements.txt --break-system-packages

# Expose the port the app runs on
EXPOSE 8000

# Run the Django development server
CMD ["/bin/bash", "-c", "python3 manage.py makemigrations excel_parcer && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 && celery -A excel_parcer worker -l info"]
